### ISSUE TITLE
/sys/class/misc/vtpm0/device/cancel No such file or directory

### ISSUE THREAD

**Issue by mimoralea** [stefanberger/swtpm#1]
Hi, I don't think this issue relates to swtpm, but I was wondering if you had an idea what the issue would be.

I'm running Fedora 21, libvirtd (libvirt) 1.2.9.3, QEMU emulator version 2.1.3 (qemu-2.1.3-9.fc21).

I compiled and checked the tpm emulator and all tests passed. I `modprobe`, and rebooted.

Then did (as root): 
```
export TPM_PATH=/tmp/myvtpm0 
swtpm_cuse -n vtpm0
systemctl restart libvirtd
```

`ls /dev/vtpm*` shows the `/dev/vtpm0` as expected

I added the tpm device to the vm using the virtual machine manager, only option available was pass-through and I typed the `/dev/vtpm0` path. Applied changes and everything seemed fine. However, when I try to start the VM I guess the issue mentioned below, any suggestions? 

```
Error starting domain: unable to set security context 'system_u:object_r:svirt_image_t:s0:c480,c764' on '/sys/class/misc/vtpm0/device/cancel': No such file or directory

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 89, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 125, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/domain.py", line 1381, in startup
    self._backend.create()
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 999, in create
    if ret == -1: raise libvirtError ('virDomainCreate() failed', dom=self)
libvirtError: unable to set security context 'system_u:object_r:svirt_image_t:s0:c480,c764' on '/sys/class/misc/vtpm0/device/cancel': No such file or directory
```

**Comment by stefanberger** [comment]
When you use the libvirt passthrough driver, the assumption is that you are using /dev/tpm0, which is supposed to be created by the Linux TPM kernel driver. The TPM driver also creates that sysfs entry. In case of a SWTPM with the CUSE interface that sysfs entry is not created and SELinux labeling will not work for the missing file.

The CUSE TPM offers a much wider interface (ioctl for out-of-band control) that is not used at all by the passthrough driver, unless QEMU is patched with the CUSE TPM support. So I would recommend not to try to run the CUSE TPM with the passthrough driver but patch QEMU with the CUSE TPM support.

Libvirt has its own extension for managing QEMU with an attached CUSE TPM, but since reviews and code acceptances have not made much progress on the QEMU level, there's no point in posting those extensions to the libvirt mailing list.

**Comment by muelli** [comment]
do you have the libvirt patches somewhere?

**Comment by stefanberger** [comment]
https://www.redhat.com/archives/libvir-list/2015-November/msg00611.html

**Comment by yankunsam** [comment]
Did the issue have a good solution now?
