### ISSUE TITLE
Status of runc PR

### ISSUE THREAD

**Issue by panburana** [stefanberger/swtpm#135]
Hi Stefan,

What is the status of the runc PR you have linked in the wiki? 
I see it hasn't really be touched since 2018.

Thanks,

Peter

**Comment by stefanberger** [comment]
I haven't had time to persue it. The maintainer wanted to move it out of runc into higher layers. However, once a namespaced IMA was to be setup by runc, the vTPM would have to be in runc as well so that a file descriptor can be opened and an ioctl called to connect the vTPM instance to the namespaced IMA instance. Namespaced IMA hasn't landed in the kernel, either, though.

**Comment by panburana** [comment]
Thanks for the response Stefan, namespace work aside, are there any open tasks that can to be done to finish up the patchset or would it best to hold off until more traction is made on namespaces for IMA?

**Comment by stefanberger** [comment]
vTPM support could be supported on the runc level, but acceptance depends on the maintainers. I haven't used it in a while, though, so I am not sure in what shape it is now versus the runc tip.
