### ISSUE TITLE
FYI: FreeBL has a Bug in Fedora, which prevents swtpm from running successful self tests 

### ISSUE THREAD

**Issue by stefanberger** [stefanberger/swtpm#15]
For details, refer to the following BZ:

https://bugzilla.redhat.com/show_bug.cgi?id=1385290

**Comment by stefanberger** [comment]
The symptom of this FreeBL bug is that certain tests are occasionally succeeding but fail most of the time:

    stefanb@node swtpm]$ sudo ./tests/test_hashing
    root     12499  0.0  0.0 118696   616 ?        Ssl  18:53   0:00 /home/stefanb/tmp/swtpm/src/swtpm/.libs/lt-swtpm_cuse -n vtpm-test-hashing
    Error: Did not get expected result from TPM_Startup(ST_Clear)
    expected:  00 c4 00 00 00 0a 00 00 00 00
    received:  00 c4 00 00 00 0a 00 00 00 1c
    [stefanb@node swtpm]$ sudo ./tests/test_hashing
    root     12597  0.0  0.0 118696   628 ?        Ssl  18:54   0:00 /home/stefanb/tmp/swtpm/src/swtpm/.libs/lt-swtpm_cuse -n vtpm-test-hashing
    Error: Did not get expected result from TPM_Startup(ST_Clear)
    expected:  00 c4 00 00 00 0a 00 00 00 00
    received:  00 c4 00 00 00 0a 00 00 00 1c
    [stefanb@node swtpm]$ sudo ./tests/test_hashing
    root     12655  0.0  0.0 118696   604 ?        Ssl  18:54   0:00 /home/stefanb/tmp/swtpm/src/swtpm/.libs/lt-swtpm_cuse -n vtpm-test-hashing
    OK
    [stefanb@node swtpm]$ sudo ./tests/test_hashing
    root     13601  0.0  0.0 118696   520 ?        Ssl  18:58   0:00 /home/stefanb/tmp/swtpm/src/swtpm/.libs/lt-swtpm_cuse -n vtpm-test-hashing
    Error: Did not get expected result from TPM_Startup(ST_Clear)
    expected:  00 c4 00 00 00 0a 00 00 00 00
    received:  00 c4 00 00 00 0a 00 00 00 1c

**Comment by bduff-sjm** [comment]
FWIW, still a problem on Fedora 28.  Using '--with-openssl' the tests complete successfully.

Or to build the rpm:
rpmbuild -ba -D "crypto_subsystem openssl" dist/libtpms.spec

**Comment by bduff-sjm** [comment]
Or for the lazy (%_topdir is nice because setting up ~/rpmbuild is lame):
# build libtpms
git clone https://github.com/stefanberger/libtpms.git
cd libtpms
git archive --format=tar.gz --prefix=libtpms-0.6.0/ -o libtpms-0.6.0.tar.gz HEAD
mkdir -p rpmbuild/SOURCES
cp libtpms-0.6.0.tar.gz rpmbuild/SOURCES/
rpmbuild -ba -D "%_topdir ${PWD}/rpmbuild" -D "crypto_subsystem openssl" dist/libtpms.spec
# install rpms in rpmbuild/RPMS/x86_64/

# build software tpm device
git clone https://github.com/stefanberger/swtpm.git
cd swtpm
git archive --format=tar.gz --prefix=swtpms-0.1.0/ -o swtpm-0.1.0.tar.gz HEAD
make dist
mkdir -p rpmbuild/SOURCES
cp swtpm-0.1.0.tar.gz rpmbuild/SOURCES
rpmbuild -ba -D "%_topdir ${PWD}/rpmbuild" "crypto_subsystem openssl" dist/swtpm.spec

**Comment by stefanberger** [comment]
Thanks for trying this out. I pretty much gave up on freebl since it doesn't offer the APIs necessary for TPM 2 ('s ECC) support. Besides that it would be a whole lot of work.

**Comment by bduff-sjm** [comment]
does the tpm2 branch also allow tpm1 devices to be created?

**Comment by stefanberger** [comment]
Yes, TPM 1.2 devices are created when one does NOT pass `--tpm2`.
