### ISSUE TITLE
TPM 2.0 support

### ISSUE THREAD

**Issue by cordney** [stefanberger/swtpm#16]
Just saw the tpm2-preview branch. 2.0 would be a nice addition. How far is the TPM 2.0 support?

**Comment by stefanberger** [comment]
TPM 2.0 support is in a preview branch here as well as in a preview branch in libtpms, which provides the actual TPM 2.0 implementation. Both need to be checked out and libtpms compiled with TPM 2.0 support for the TPM 2.0 support in this project to work.

The TPM 2.0 support in the preview branch in libtpms **currently** writes the TPM's state information in (normalized) Big Endian format, so that the state is migrateable between machines of different endianess. This would primarily be desirable for vTPM integration with QEMU, since QEMU writes all devices' state is in Big Endian format.

**Comment by stefanberger** [comment]
Otherwise I would say that TPM 2.0 is quite far along and --tpm2 is the only parameter that needs to be passed to swtpm to activate TPM 2.0 functionality versus TPM 1.2 functionality.

**Comment by cordney** [comment]
Thanks, will give it a try.
