### ISSUE TITLE
Integrate swtpm into nova-compute

### ISSUE THREAD

**Issue by itsucks** [stefanberger/swtpm#20]
Hi, I've been trying to integrate swtpm into nova-compute. I added qemu commandline in libvirt.xml
```
<qemu:commandline>
    <qemu:arg value='-tpmdev'/>
    <qemu:arg value='cuse-tpm,id=tpm0,path=/dev/vtpm0'/>
    <qemu:arg value='-device'/>
    <qemu:arg value='tpm-tis,tpmdev=tpm0'/>
</qemu:commandline>
```  
Then I start the CUSE TPM manually.
```
# modprobe cuse
# mkdir /tmp/myvtpm0
# chown -R tss:root  /tmp/myvtpm0
# swtpm_setup --tpm-state /tmp/myvtpm0  --createek
# export TPM_PATH=/tmp/myvtpm0
# swtpm_cuse -n vtpm0
```  
Then I start a nova instance, and got error  
```
qemu-system-x86_64: -tpmdev cuse-tpm,id=tpm0,path=/dev/vtpm0: Cannot access TPM device using '/dev/vtpm0': Operation not permitted
```
I googled this error and got this [Unable to start vtpm vm through libvirt xml file](https://github.com/stefanberger/swtpm/issues/7). I tried 'umount /sys/fs/cgroup/devices' as discribed in the issue. Then I start the nova instance again.
```
libvirtError: internal error: process exited while connecting to monitor: qemu-system-x86_64: -tpmdev cuse-tpm,id=tpm0,path=/dev/vtpm0: Cannot access TPM device using '/dev/vtpm0': Permission denied
```  
I tried to chmod 777 to /tmp/myvtpm0 and /dev/vtpm0, it didn't work. Could someone please help me out?

**Comment by stefanberger** [comment]
Possible problems:
- SELinux label is missing on /dev/vtpm0; a solution would be to run SELinux in permissive mode (`setenforce 0`)
- libvirt sets up QEMU in such a way that devices need to be in a device cgroup for them to be accessible by QEMU; I am not sure what to do in this case, but maybe one could try to unmount the device cgroup to deactivate this security feature.

As mentioned in that other thread, there's a CUSE TPM driver for libvirt, but it's not currently publicly available primarily since QEMU hasn't accepted the CUSE TPM.
