### ISSUE TITLE
Debian/Ubuntu Packaging seems ok, why isn't it in the Archive?

### ISSUE THREAD

**Issue by cpaelzer** [stefanberger/swtpm#216]
Hi,
I've seen [Debian packaging](https://github.com/stefanberger/swtpm/tree/master/debian) in your repository - and got reported from some users that it works fine for them.

On the other side I know that a [Debian ITP](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=941199) exists for a while but not moving forward.

Might I ask if there are known blockers that so far prevented this from showing up in Debian/Ubuntu that are missing from just looking at it?

**Comment by stefanberger** [comment]
The Ubuntu build system was failing the swtpm test cases (for PPAs at least) until a while ago due to the seccomp policy being applied to swtpm while running the test cases and swtpm ended up crashing for some reason which I couldn't recreate on a normal Ubuntu installation. I have fixed this recently for the PPAs. If someone wanted to be the official packager for Debian/Ubuntu (other than PPA), please let me know. I have a per-Ubuntu series PPA here:

https://launchpad.net/ubuntu/+ppas?name_filter=swtpm

**Comment by stefanberger** [comment]
I just built swtpm-0.3.0 from the stable-0.3.0 branch for my PPA. It was easy and should be just as easy for an official Ubuntu / Debian build.

**Comment by stefanberger** [comment]
So I am not sure what is holding up the packaging for Debian/Ubuntu. The swtpm test run problems (related to some seccomp issue) have been solved and I have been able to build packages for my PPA on Ubuntu's build server. Does this help? I think the rest is outside my control.

**Comment by cpaelzer** [comment]
Hi @stefanberger - I think we were just in [Feature Freeze](https://wiki.ubuntu.com/FocalFossa/ReleaseSchedule) already. I know that [xnox](https://launchpad.net/~xnox) considered uploading it anyway but seems he didn't get to or decided against it.
I'd expect that once 20.10 is open that is more likely to happen.

**Comment by stefanberger** [comment]
Can you close the issue?

**Comment by cpaelzer** [comment]
Agreed, nothing to resolve on your side right now.

**Comment by stefanberger** [comment]
FYI: I now tagged v0.3.1: https://github.com/stefanberger/swtpm/releases/tag/v0.3.1
