### ISSUE TITLE
Issue when verifying EK against swtpm-localca-rootca-cert.pem

### ISSUE THREAD

**Issue by eduardolfalcao** [stefanberger/swtpm#264]
Hi Stefan.

Could you help me to understand how to address this issue of verifying the EK against the RootCA?

First, I deploy swtpm with the following command:

`sudo swtpm_setup --tpmstate ${VTPM_DIR_PATH} --createek --create-ek-cert --create-platform-cert --allow-signing --tpm2`

I noticed that the following keys and certs were generated: certserial, plat.cert.pem, signkey.pem, swtpm-localca-rootca-cert.pem, issuercert.pem.

After booting my VM through Qemu, I used the following TPM command to retrieve the public part of the EK:

`tpm2_createek -c ek.handle -G rsa -u ek.pub -P endorsementPassword -f pem`

Finally, I run the openssl verify command:
`sudo openssl verify -x509_strict -CAfile swtpm-localca-rootca-cert.pem ek.pub`

output:
ek.pub: CN = unknown
error 20 at 0 depth lookup:unable to get local issuer certificate

How do I configure the CN into my EK?

Best regards

**Comment by stefanberger** [comment]
Since more people may be interested in this I extended the wiki page with the steps to perform. 

Please have a look at: https://github.com/stefanberger/swtpm/wiki/Certificiates-created-by-swtpm_setup#verifying-your-ek-cert-against-the-ca

You need to follow the steps above to read the certificate out of its NVRAM location first to get the ekcert.der file. 

Let me know if this works for you.

**Comment by eduardolfalcao** [comment]
Hi @stefanberger. 

Thank you very much. It worked like a charm. :)

**Comment by stefanberger** [comment]
good to know :-)
