### ISSUE TITLE
SWTPM socket  --flags not-need-init 

### ISSUE THREAD

**Issue by prettyDamCool** [stefanberger/swtpm#274]
The follow error messages happens whe ruing the command. SWTPM tools has bee compiled from source with some added algorithms that have worked, when running within the SWTPM the following error is displayed:

```
# swtpm socket --tpmstate dir=/tmp/myvtpm --tpm2 --ctrl type=tcp,port=2322,bindaddr=172.17.0.3 --server type=tcp,port=2321,bindaddr=172.17.0.3 --flags not-need-init

libtpms/tpm2: Entering failure mode; code: 4, location: SetBit line 98
Segmentation fault (core dumped)

```
When it has been ran without  --flags not-need-init
You cant connect to the SWTPM 
Would you know of what triggers this issue and what file from source breaks?

**Comment by stefanberger** [comment]
The above command works for me without a problem, so I cannot recreate your problem. You have to tell me how you got there.

> SWTPM tools has bee compiled from source with some added algorithms that have worked, when running within the SWTPM the following error is displayed:

Did you modify libtpms with 'added algorithms' ? If so, you would have to tell me how you modified it and which version you took, because we don't necessarily support other configurations than what the profile (TPMProfile.h) specifies. Basically the libtpms configuration that is supported must pass the 'make check' test of `swtpm` project.

Does it help if you remove any previous state files from `/tmp/myvtpm`?

**Comment by prettyDamCool** [comment]
Yes, some modifications have bee made  to libtpms:
**/src/tmp2**
CommandAttributeData.h, CommandDispatchData.h, Cryptutil.c
Implementation.h, InternalRoutines.h, Marshal.c, Marshal_fp.h, Object.c, TpmTypes.h,
Unmarshal.c and Unmarshal_fp.h.

These are used to define/call the new algorithms:
**/tpm_sim/tss/utils**
CommandAttributeData.c,
Commands.c, Commands_fp.h, certify.c, create.c, createloaded.c, createprimary.c,
loadexternal.c, objecttemplates.c, objecttemplates.h, quote.c, sign.c, tssauth20.c, tssmarshal.c,
tssprint.c, Unmarshal.c and verifysignature.c.

All the modification do is call the newly added algorithms much like how the default algorithms have been implemented, the modifications pass all the data as AES has bee implemented as a example.

-When doing make check it passes fine.

**Comment by stefanberger** [comment]
Sorry, but I cannot help you with your modifications. You'll have to figure out what goes wrong there.
