### ISSUE TITLE
tpm_cuse: Detected CUSE TPM but could not send INIT

### ISSUE THREAD

**Issue by lwyeluo** [stefanberger/swtpm#3]
Hi, I tried to build the vTPM environment with swtpm、libtpms and qemu-tpm, but when I launched the qemu with the following command, it shows, "tpm_cuse: Detected CUSE TPM but could not send INIT: software caused connection abort".

Here are the commands I used. Thanks.

"qemu-boot-centos")
        qemu-system-x86_64 -display sdl -enable-kvm -cdrom /home/luowu/CentOS-7-x86_64-DVD-1511.iso \
    -m 1024 -boot d -bios $SEABIOS/bios.bin -boot menu=on -tpmdev \
    cuse-tpm,id=tpm1,path=/dev/vtpm1 \
    -device tpm-tis,tpmdev=tpm1 /qemu/image/centos.img
        ;;
"qemu-start-centos")
        qemu-system-x86_64 -display sdl -enable-kvm \
    -m 1024 -boot c -bios $SEABIOS/bios.bin -boot menu=on -tpmdev \
    cuse-tpm,id=tpm1,path=/dev/vtpm1 \
    -device tpm-tis,tpmdev=tpm1 /qemu/image/centos.img
        ;;
"create-vtpm1")
        chown -R tss:root  /tmp/myvtpm1
        swtpm_setup --tpm-state /tmp/myvtpm1  --createek
        export TPM_PATH=/tmp/myvtpm1
        swtpm_cuse -n vtpm1
        ;;

**Comment by stefanberger** [comment]
I assume the CUSE TPM is running once you run the above commands.
What happens when you run the following command?

swtpm_ioctl -i /dev/vtpm1

Can you run it twice ?

**Comment by lwyeluo** [comment]
Thanks for your reply. 

When I run "swtpm_ioctl -i /dev/vtpm1", it returns "TPM result from PTM_INIT: 0x7c", and the same result if I run the commard twice.

Then I tried to run the 'qemu-start-centos' with 'img' followed by 'create-vtpm1' with 'log'. After the centos successful launched, the log file tells me "CUSE TPM successful initialized" for many times, and in the centos, I typed:

dmesg | grep tpm

It shows that a tpm error(28) occurred attempting to start the tpm. Maybe I need to delete /tmp/myvtpm1 and run the commands again?

**Comment by lwyeluo** [comment]
Well, I wanted to add some debug info in the cuse_tpm.c, and then 'make'. There is a error that 'FAIL: test_commandline, Test 1 failed, tpm_bios did not work' when I run 'make check'. Is the tpm error(28) caused by this?

**Comment by lwyeluo** [comment]
Hi, I guess that the error("TPM result from PTM_INIT: 0x7c") is due to the variable named 'res' not having a default value in cuse_tpm.c at line 987(‘case PTM_INIT’ in function ptm_ioctl). So I tried to add a line:  'res = TPM_SUCCESS;'   It seems to work.

**Comment by stefanberger** [comment]
Yes, that was the problem. I fixed this. Please pull from the repo and give it another try. Thanks.

**Comment by lwyeluo** [comment]
Yeah, it works. Thanks for your help. 
By the way, can i run vtpm in other linux os like ubuntu?

**Comment by stefanberger** [comment]
For Ubuntu you need 15.04 or later due to gnutls version dependency.

**Comment by lwyeluo** [comment]
I am sorry to trouble you again. I tried to run libtpms in ubuntu15.10, and it reported a error that 'could not find AES_CreateContext()". I had installed libnss3-dev. I do not know which package I need to install. Is there any solution to solve this problem? Thanks.

**Comment by stefanberger** [comment]
AES_CreateContext() is supposed to be in /usr/include/nss3/blapi.h. This file, I believe, was missing in older versions of that libraray. But it should be there now:

http://packages.ubuntu.com/vivid/amd64/libnss3-dev/filelist

On Ubuntu I think you should use configure libtpms with '--with-openssl' and do the same on 'swtpm'. That way both are going to use openssl rather than freebl.

So for libtpms and swtpm the following should work:

./configure --prefix=/usr --with-openssl 
make 
make check
sudo make install

I just added a check to swtpm's configure.ac to make sure swtpm and libtpms use the same crypto library. They both have to use the same crypto lib. This is due to problems related to hash update functions with the same names being provided in both of them. This results in crashes when mixing freebl and openssl in swtpm and libtpms.

**Comment by lwyeluo** [comment]
I made it in ubuntu 15.10. 
Thank you so much.
