### ISSUE TITLE
tpm2_load results in "tpm2_savecontext: out of backing store"

### ISSUE THREAD

**Issue by osresearch** [stefanberger/swtpm#362]
Trying to load an ephemeral ECC attestation key in the endorsement key hierarchy fails with a kernel error. This procedure works on real hardware as part of generating quotes, although hangs in swtpm (ab40d27)

```
tpm2 flushcontext --transient-object
tpm2 flushcontext --loaded-session
tpm2 flushcontext --saved-session

tpm2 createek --ek-context ek.ctx --key-algorithm rsa --public ek.pub

tpm2 startauthsession --session session.ctx --policy-session
tpm2 policysecret --session session.ctx --object-context endorsement
tpm2 create \
  --parent-context ek.ctx \
  --parent-auth session:session.ctx \
  --key-algorithm ecc:ecdsa:null \
  --attributes 'fixedtpm|fixedparent|sensitivedataorigin|userwithauth|restricted|sign|stclear' \
  --public ak-pub.key \
  --private ak-priv.key

tpm2 startauthsession --session session.ctx --policy-session
tpm2 policysecret --session session.ctx --object-context endorsement
tpm2 load \
  --parent-context ek.ctx \
  --auth session:session.ctx \
  --key-context ak.ctx \
  --public ak-pub.key \
  --private ak-priv.key
```

The `tpm2_load` command results in:
```
[  154.643696] tpm tpm0: tpm2_save_context: out of backing storage
[  154.646634] tpm tpm0: tpm2_commit_space: error -12
```
and the command hangs.

Flushing sessions and loaded objects before attempting the `tpm2_load` does not change the error.

**Comment by osresearch** [comment]
A much simpler failure comes from the example in the `tpm2_createak` man page:
```
tpm2 createek -c ek.handle -G rsa -u ek.pub
tpm2 createak -C ek.handle -c ak.ctx -u ak.pub -n ak.name
[   18.790144] tpm tpm0: tpm2_save_context: out of backing storage
[   18.793296] tpm tpm0: tpm2_commit_space: error -12
```

The swtpm directory was created with an empty config file, might that be the problem?
```
swtpm_setup \
                --tpm2 \
                --createek \
                --tpmstate vtpm \
                --config /dev/null
```

**Comment by stefanberger** [comment]
You are hitting this issue here: https://github.com/stefanberger/libtpms/issues/147

You need at least a [5.8.2 kernel](https://elixir.bootlin.com/linux/v5.8.2/source/drivers/char/tpm/tpm2-space.c) or one of the long-term stable ones to which the following patch has been applied to: https://github.com/torvalds/linux/commit/6c4e79d99e6f42b79040f1a33cd4018f5425030b

So you have to either upgrade to the new kernel or use libtpms from the stable-0.7.0 branch. If you downgrade to libtpms-0.7.x from libtpms-0.8 you need to find the TPM 2 state file and remove it since the older libtpms (0.7.x) cannot read the newer libtpms (0.8) state. In your case just delete the `vtpm` directory and re-create it.

**Comment by osresearch** [comment]
Downgrading to `stable-0.7.0` of libtpms appears to work. Thanks for the pointer.
