### ISSUE TITLE
hard dependency to tss user account

### ISSUE THREAD

**Issue by jsakkine-intel** [stefanberger/swtpm#37]
It seems that there is a hard dependency to fixed a user account

```
$ swtpm_setup
Could not get account data of user tss.
```
I'd use this for kernel testing without any specific user space stack.

**Comment by stefanberger** [comment]
`swtpm_setup` for TPM 1.2 depends on TrouSerS's tcsd for 'manufacturing' a TPM 1.2, which in turn typically requires the tss user. With `--tpm2` it would not need that. What do you intend to do and did you install all dependencies?

**Comment by jsakkine-intel** [comment]
I try to use for  TPM 1.2 kernel testing with minimalistic kernel and initrd image:

https://github.com/jsakkine-intel/buildroot-tpmdd

To compile this:

```
make tpmdd_defconfig
make
```

I've packaged libtpms and swtpm for BuildRoot for this purpose (see the commits almost on top):

https://github.com/jsakkine-intel/buildroot-tpmdd/commits/master

**Comment by stefanberger** [comment]
`swtpm_setup` helps with creating an EK for example and certificates and writing the certs into NVRAM. Do you need that for testing ? If not, you don't need to run it. Otherwise TPM_CreateEndorsementKeyPair creates an EK for a TPM 1.2 and doesn't need crypto for setting up a session, so it's easy enough to send it as raw bytes if you need to dump the EK.

**Comment by stefanberger** [comment]
Btw, there is no **hard** dependency on the tss user account. One can pass `--with-tss-user=<user name>` and `--with-tss-group=<group name>` to the swtpm configure script to select a different user than 'tss' if that user doesn't exist on the system. 'root' can also be chosen.

**Comment by bduff-sjm** [comment]
So in using this with qemu to create the endorsement key pair, I use the instructions here:
https://github.com/qemu/qemu/blob/master/docs/specs/tpm.txt
As in there:
swtpm socket --tpmstate dir=/tmp/mytpm1   --ctrl type=unixio,path=/tmp/mytpm1/swtpm-sock --log level=20
# and that works, but I have no EK, so instead of creating with something like (which fails):
swtpm_setup --tpmstate dir=/tmp/mytpm1 --create-platform-cert
# I should do a TPM_CreateEndorsementKeyPair call in my VM (guest), I should do something like:
tpm_createek

**Comment by bduff-sjm** [comment]
```
$ swtpm_setup --tpm-state /tmp/mytpm2 --create-platform-cert --create-ek-cert
Setting groupid to tss (59) failed: Operation not permitted
```
So I need to run as root:
```
$ sudo swtpm_setup --tpm-state /tmp/mytpm2 --create-platform-cert --create-ek-cert
Starting vTPM manufacturing as tss:tss @ Fri 23 Mar 2018 12:35:13 PM CDT
TPM is listening on TCP port 63156.
Successfully created EK.
TSS is listening on TCP port 34002.
...
```
And then just chown the tpm-00.permall file back to me and run "swtpm socket ..."

**Comment by stefanberger** [comment]
Unfortunately this is the pain with tcsd at the moment.

**Comment by stefanberger** [comment]
... libvirt would run this program with `--runas tss` for example.
