### ISSUE TITLE
swtpm + qemu/tpm emulator leaves TPM2 chip in lockout state

### ISSUE THREAD

**Issue by anatol** [stefanberger/swtpm#381]
I am using swtpm with qemu for testing. swtpm creates a chardev and qemu uses it.

The first time I start qemu this way everything seems fine. The next time I run qemu and try to use tpm from the VM it gives me error: `unable to load data: warning code 0x21 : authorizations for objects subject to DA protection are not allowed at this time because the TPM is in DA lockout mode`. It might be related to unclean shutdown but it is not clear where this issue comes from.  My app does not do any thing special wrt TPM state. And I would expect that QEMU properly clears TPM on VM shutdown.

**Comment by stefanberger** [comment]
I have not come across this issue. You would have to give an exact description of your environment and what you are doing, such as how you are generating the key and what you then do until you encounter the issue so that one can reproduce the issue.

> It might be related to unclean shutdown but it is not clear where this issue comes from. My app does not do any thing special wrt TPM state. And I would expect that QEMU properly clears TPM on VM shutdown.

If you don't cleanly shut down a VM then that may be causing an issue. It's the Linux kernel that has to send a TPM_Shutdown() to the TPM 2: https://elixir.bootlin.com/linux/latest/source/drivers/char/tpm/tpm-chip.c#L294

**Comment by anatol** [comment]
> If you don't cleanly shut down a VM then that may be causing an issue. 

Thanks for the pointer. My application uses https://github.com/anatol/vmtest golang library to start/stop a QEMU VM. It turns out that the library uses QEMU monitor and issues `quit` command at the end of the test. After changing this command to `system_powerdown` I do not see the issue with TPM.

Thank you for your help!
