### ISSUE TITLE
swtpm fails while executing autogen.sh

### ISSUE THREAD

**Issue by ajaik91** [stefanberger/swtpm#398]
I receive a error - 
**checking for TPMLIB_ChooseTPMVersion in -ltpms... no
configure: error: "libtpms 0.6 or later is required"**

Under my /usr/lib , I have the libraries - 
libtpms.a                  
libtpms.la                 
libtpms.so                 
libtpms.so.0               
libtpms.so.0.8.0

I have the libtpms with version 0.8.0 installed in my Ubuntu 16 machine and yet I see this error. Am I missing some step here. Please help me?

**Comment by stefanberger** [comment]
I have seen this before but I don't remember what the cause may be. I would recommend to go back to libtpms and try running the following (this --libdir is better for Ubuntu).
```
sudo make uninstall
./autogen.sh --prefix=/usr --with-tpm2 --with-openssl --libdir=/usr/lib/x86_64-linux-gnu/
make -j8
make -j8 check
sudo make install
```

Otherwise you could try building a package of libtpms and install it: https://github.com/stefanberger/libtpms/wiki#build-a-package-on-ubuntu

**Comment by ajaik91** [comment]
Hello Stefan,

Thanks for the quick reply. I still have the same issue. configure.ac uses AC_CHECK_LIB  to check if the library is installed. But i see the library present under /usr/lib. 

configure.ac , line no 171 -
**LDFLAGS="$LDFLAGS $LIBTPMS_LIBS"
CFLAGS="$CFLAGS $LIBTPMS_CFLAGS"
AC_CHECK_LIB(tpms,
             TPMLIB_ChooseTPMVersion,[true],
             AC_MSG_ERROR("libtpms 0.6 or later is required")
)
AC_SUBST([LIBTPMS_LIBS])**


The above check is failing.

**Comment by stefanberger** [comment]
I cannot recreate the problem here. Maybe `config.log` has a hint.

**Comment by stefanberger** [comment]
It works for me when libtpms is install in /usr/lib, possibly because of the linker search path including this dir:
```
# ld --verbose | grep SEARCH_DIR
SEARCH_DIR("=/usr/local/lib/x86_64-linux-gnu"); SEARCH_DIR("=/lib/x86_64-linux-gnu"); SEARCH_DIR("=/usr/lib/x86_64-linux-gnu"); SEARCH_DIR("=/usr/lib/x86_64-linux-gnu64"); SEARCH_DIR("=/usr/local/lib64"); SEARCH_DIR("=/lib64"); SEARCH_DIR("=/usr/lib64"); SEARCH_DIR("=/usr/local/lib"); SEARCH_DIR("=/lib"); SEARCH_DIR("=/usr/lib"); SEARCH_DIR("=/usr/x86_64-linux-gnu/lib64"); SEARCH_DIR("=/usr/x86_64-linux-gnu/lib");
```

**Comment by stefanberger** [comment]
The missing symbols are related to openssl. Maybe try re-installing and/or updating the libssl & libssl-dev packages? You have to get rid of those issues first.

**Comment by ajaik91** [comment]
I have openssl 1.1.0 running in my Ubuntu 16. But libssl packages are only configured for 1.0.2. Has this simulator been tested for Ubuntu 16.

**Comment by stefanberger** [comment]
I think you should go with Ubuntu 18.04. On 16.04 there may be the issue with an outdated python package (python3-cryptography) that swtpm relies on, though you could try to use pip3 to update that one if it becomes necessary, though I would consider 16.04 to be old at this point. But libtpms compiles and the tests work just fine on 16.04. I just tried this when installing it to `/usr/lib/x86_64-linux-gnu` (but, yes, it does NOT work when installed to `/usr/lib`). So, please follow the instructions above for how to configure libtpms on 16.04.

test_parameters of swtpm fails with this error message due to outdate python3-cryptography:
```
[...]
Test 2: Traceback (most recent call last):
  File "/root/swtpm/src/swtpm_setup/swtpm_setup", line 7, in <module>
    main()
  File "/root/swtpm/src/swtpm_setup/py_swtpm_setup/swtpm_setup.py", line 1037, i
    swtpm_keyopt, fds_to_pass)
  File "/root/swtpm/src/swtpm_setup/py_swtpm_setup/swtpm_setup.py", line 418, in
    ret = tpm12_take_ownership(flags, ownerpass, srkpass, pubek, swtpm)
  File "/root/swtpm/src/swtpm_setup/py_swtpm_setup/swtpm_setup.py", line 360, in
    tpm12_get_srkpass_digest(flags, srkpass), pubek)
  File "/root/swtpm/src/swtpm_setup/py_swtpm_setup/swtpm.py", line 1053, in take
    enc_owner_auth = pubekkey.encrypt(ownerpass_digest, oaep)
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/openssl/rsa.
    return _enc_dec_rsa(self._backend, self, plaintext, padding)
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/openssl/rsa.
    raise ValueError("This backend does not support OAEP labels.")
ValueError: This backend does not support OAEP labels.
ERROR: Test with parameters '--take-ownership' failed.
```

To get rid of this issue run this command -- all test of swtpm (`make check`) pass then.

```
# /usr/bin/python3 -m pip install --upgrade cryptography
```

**Comment by stefanberger** [comment]
@ajaik91 Does it work now?

**Comment by stefanberger** [comment]
python3 cryptography 2.1.4 is the minimum
