### ISSUE TITLE
Error code 0x000009a2 causes partial cases in the test/integration directory to fail

### ISSUE THREAD

**Issue by DingXinX** [stefanberger/swtpm#74]
I worked on clean Ubuntu from qemu, following the deployment implementation of the VTPM.

Run tpm2-tss/script/int-log-compiler-ptpm.sh with target device "/dev/tpm0" to test all cases in directory test/integration or configure to configure "--with-ptpm" and "--with-ptpmtests" parameters, then make check. The following failure log is obtained:

FAIL: test/integration/esys-pcr-auth-value
Execute the test script
WARNING:esys:src/tss2-esys/api/Esys_PCR_SetAuthValue.c:294:Esys_PCR_SetAuthValue_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_PCR_SetAuthValue.c:111:Esys_PCR_SetAuthValue() Esys Finish ErrorCode (0x000009a2)
ERROR:test:test/integration/esys-pcr-auth-value.int.c:67:test_esys_pcr_auth_value() Error: PCR_SetAuthValue ErrorCode (0x000009a2)
Script returned 1
FAIL test/integration/esys-pcr-auth-value.int (exit status: 1)

FAIL: test/integration/esys-clear
Execute the test script
WARNING:esys:src/tss2-esys/api/Esys_Clear.c:284:Esys_Clear_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_Clear.c:103:Esys_Clear() Esys Finish ErrorCode (0x000009a2)
ERROR:test:test/integration/esys-clear.int.c:70:test_esys_clear() Error: Clear ErrorCode (0x000009a2)
Script returned 1
FAIL test/integration/esys-clear.int (exit status: 1)

**Comment by stefanberger** [comment]
The errorcode `0x9a2` means "TPM_RC_BAD_AUTH - authorization failure without DA implications Session number 1". Has a password already been set and a different one is being used in the test case? 

The 2nd test case runs a TPM2_Clear() with platform hierarchy authorization handle (https://github.com/tpm2-software/tpm2-tss/blob/master/test/integration/esys-clear.int.c#L58). This cannot work when a firmware has set the platform authorization. When I use the IBM tools as follows I also see this error when running inside a VM with SeaBIOS initializing the TPM 2 and setting the platform hierarchy password to a random password:
```
 #> tssclear -hi p
 clear: failed, rc 000009a2
 TPM_RC_BAD_AUTH - authoritzation failure without DA implications Session number 1
```
Regarding the 1st test case: I see that later on in the esys-pcr-auth-value.int.c test Platform authorization is needed (https://github.com/tpm2-software/tpm2-tss/blob/master/test/integration/esys-pcr-auth-value.int.c#L86).  This is the same problem then due to TPM 2 initialization by the firmware as in the 2nd test case you are showing. Though I am not sure why the test case errors out when setting the PCR's AuthValue.

There are some operations that can only be run with a TPM 2 whose platform authorization hasn't been set. I would say the 2nd test case's failure is related to this issue. Likely the test cases should check the return code and indicate that the test cannot run under the current TPM 2 configuration.

**Comment by bzhu5** [comment]
Stefan, thanks for your comment, I think your explanation does make sense. 
i just checked this doc - "Platform Hierarchy (Physical Presence)" in page #101, https://www.trustedcomputinggroup.org/wp-content/uploads/PC-ClientSpecific_Platform_Profile_for_TPM_2p0_Systems_v21.pdf

my understanding is that if the BIOS firmware (either physical bios or virtual bios) is compliant to TCG spec,  then bios shall change platformauth to a random value, then discard it.

so, in this case, the TPM_RC_BAD_AUTH is expected error code.

**Comment by bzhu5** [comment]
> There it states for TPM2_PCR_SetAuthValue: "This command has no meaning for a PCR as PC
Client TPMs do not implement authorization for PCR"

how do we understand the "as PC Client TPMs do not implement authorization for PCR"? it is marked as "O" optional. but, typically PC TPMs never implements this ?

**Comment by stefanberger** [comment]
> how do we understand the "as PC Client TPMs do not implement authorization for PCR"? it is marked as "O" optional. but, typically PC TPMs never implements this ?

I guess it will not be implemented for PC TPMs.

**Comment by stefanberger** [comment]
I just checked in a patch to libtpms: https://github.com/stefanberger/libtpms/commit/9582b580365614ac18c9bbf37f7af43acc2940da. Try to update libtpms and run the test again. I don't think this should make a difference,  though.
